Fill out all fields for the Instance type
canonical/nlxd-rs pull request #14
Opened 2024-03-24 23:18 UTC by samuelallan72

This should completely cover the fields described in the api documentation for [GET /1.0/instances](https://documentation.ubuntu.com/lxd/en/latest/api/#/instances/instance_get).

Note that `restore` is documented there, but does not appear in actual responses (and shouldn't appear; this appears to be a docs issue).  I opened https://github.com/canonical/lxd/issues/12993 to report it.

Fixes: #7

2024-05-29 11:39 UTC, TheSignPainter98 requested changes
This looks like a nice step forward! Here are a couple of things I think we should consider

2024-05-29 11:39 UTC, TheSignPainter98 commented on src/client.rs
> +    // TODO: enum for http codes - use serde_repr
Using a `u32` here seems problematic to me. Looking around, it could be nice to use an `http::StatusCode` for this instead, although to get this to play nicely with `serde`, we may need to annotate it with `#[serde(with = "...")]` with something which wraps `StatusCode::try_from`

2024-05-29 11:39 UTC, TheSignPainter98 commented on src/client.rs
> +    /// Try to get an instance by its name.
I think the 'Try to' can be omitted here, the compiler will force acknowledgement of the `Result` anyway so it's okay to be consistent with the doc of the previous method

2024-05-29 11:39 UTC, TheSignPainter98 commented on src/instance.rs
> +}
Using an enum with `repr(16)` doesn't feel quite idiomatic to me (it feels more C-like to me). I think instead it could be nice to use a wrapper type and make these constants:
```rust
#[derive(Copy, Clone, Debug)]
pub struct InstanceStatus(u16);

impl InstanceStatus {
    pub const OPERATION_CREATED: Self = Self(100);
    ...

    pub fn into_inner(self) -> u16 {
        self.0
    }
}

impl TryFrom<u16> for InstanceStatus { ... }
```
We may need to implement `Deserialise` ourselves, but the `TryFrom` implementation should hopefully make this trivial

2024-06-07 18:08 UTC, TheSignPainter98 commented on src/instance.rs
> +}
Actually I think I was wrong with this one, the alternatives seem to be worse so let's stick with this. The only think I'd add is that I think we should add `#[non_exhaustive]` to prevent future codes causing breaking changes

2024-06-07 18:09 UTC, TheSignPainter98 commented on src/client.rs
> +    // TODO: enum for http codes - use serde_repr
Hold on, could this be changed to `InstanceStatus` or another type we already have? Otherwise leaving the todo seems okay for now

2024-06-11 00:27 UTC, samuelallan72 commented on src/client.rs
> +    // TODO: enum for http codes - use serde_repr
I don't think so - I did investigate at the time, but this is the raw http code, not an instance status.

2024-06-11 00:35 UTC, samuelallan72 commented on src/instance.rs
> +}
Added.  :) Although I reckon it would be rare for a new instance status to be added? :thinking:

2025-06-22 00:35 UTC, samuelallan72 commented
@TheSignPainter98 @NucciTheBoss I'll actually close my PRs here now that I've left the company and no longer have access to this repository. If I contribute in the future, I can open PRs from a personal fork. :)

2025-06-22 00:35 UTC, closed without merging