Add support for listing and retrieving images
canonical/nlxd-rs pull request #18
Opened 2024-03-24 23:23 UTC by samuelallan72

note: depends on https://github.com/canonical/nlxd-rs/pull/15

2024-05-29 12:50 UTC, TheSignPainter98 requested changes
This is coming along nicely! Here are a few points to think about

2024-05-29 12:50 UTC, TheSignPainter98 commented on examples/images.rs
> +    println!("{:#?}", &image_fingerprints);
Outputting with `Debug` in an example looks like something's slightly off. Also these two `println!` calls seem to output more or less the same thing? Perhaps adding some text into the print statement and outputting something specific could be useful?

2024-05-29 12:50 UTC, TheSignPainter98 commented on src/client.rs
> +    pub fn images(&self) -> Result<Vec<String>> {
I think we can help out the person using this API by replacing `String` here with some `ImageID` type. Also, it seems problematic that `client.images()` doesn't actually return images... this is actually nicely demonstrated by the example, where the return of this function has to be assigned into `image_fingerprints` rather than some `images` declaration ;)

2024-05-29 12:50 UTC, TheSignPainter98 commented on src/client.rs
> +            .filter_map(|s| s.strip_prefix("/1.0/images/").map(|s| s.to_owned()))
Can the `.map(|s| ...)` be moved out of the `.filter_map`? I think flatter call chains are easier to read as it encourages simple steps.

Also, what happens if an images _doesn't_ have the `/1.0/images/` prefix? Is it worth returning an error in this case?

2024-05-29 12:50 UTC, TheSignPainter98 commented on src/images.rs
> +#[serde(rename_all = "snake_case")]
I think `snake_case` relies on their being no uppercase letters after the start of these enum variants, perhaps `lowercase` would be cleaner?

2024-05-29 12:50 UTC, TheSignPainter98 commented on src/images.rs
> +pub struct Bytes(u64);
The name `Bytes` represents the what but doesn't hint at the why, when reading this, I would have expected the content to have been `Vec<u8>` rather than `u64`. Instead, perhaps we could call this `SizeBytes`? I'm actually unsure whether we need this extra type, the doc string on the `size` field already covers this. Perhaps that field could be renamed to `size_bytes`, `num_bytes` or `nbytes`?

2024-05-29 12:50 UTC, TheSignPainter98 commented on src/images.rs
> +    // TODO: these should be datetimes - added in https://github.com/NucciTheBoss/nlxd/pull/19/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542
This points to a closed issue :) I think it would be better to add a comment to this PR to the effect of 'This PR awaits #15', then fix this before merging. I think this is a good case to put this PR back into draft just to avoid any accidental merging

2024-05-29 12:50 UTC, TheSignPainter98 commented on src/images.rs
> +    image_type: String,
That sounds like this field should have type `Option<String>` :P Is it possible to change this? If so, I think this comment is redundant.

Hold on, we have the `ImageType` type here, could this be used here?

2024-05-29 12:50 UTC, TheSignPainter98 commented on src/images.rs
> +    Simplestreams,
The name `Simplestreams` looks awkward, would `rename_all = "lowercase"` fix this? It would be nice to capitalise this on the Rust side

2024-06-07 18:56 UTC, TheSignPainter98 commented on src/client.rs
> +    pub fn images(&self) -> Result<Vec<String>> {
We could instead return some lazy `Image` type, where accessing its properties would be done by fallible method. This could work nicely, I'm just concerned about timing---the first time we access a property, we'd effectively take a snapshot of the image, so future property accesses wouldn't get updated. This could be resolved with some `refresh` method to force the cached value to be updated, but I'm wondering would this be too arcane?

What if instead, `images` returned an `impl Iterator<Item = Result<Image>>`? So it's obvious that when the item is extracted from the iterator that's it at that time? If the user didn't want to get the images, there could be a separate `fn image_ids(&self) -> impl Iterator<Item = ImageId>`, where we'd have some way to get an image using a given image ID (perhaps some `Image::retreive(image_id)`)?

2024-06-11 03:04 UTC, samuelallan72 commented on src/client.rs
> +    pub fn images(&self) -> Result<Vec<String>> {
Thanks for these notes.  I don't think I'm a fan of the first option (lazy image type) due to the concerns about caching and refreshing you noted.  I'd also prefer any network requests be explicit, and a network request on accessing an attribute seems unexpected.

I like the idea of returning an iterator, that could be interesting.  We can definitely have a separate image_ids method.

> perhaps some `Image::retreive(image_id)`

Ah interesting, this goes back to a design discussion that I'm not sure we resolved completely?  To pattern things around a single client with methods vs 'objects' with methods to retrieve related things.  eg.

- `client.get_image_by_id(image_id)`
- vs `Image::retrieve(client_config, image_id)`

2024-06-11 03:28 UTC, samuelallan72 commented on src/images.rs
> +    image_type: String,
True, this can absolutely be an `Option<ImageType>`.  I don't know what it means for the image type to be empty here though, so I opened an issue on lxd: [canonical/lxd#13586](https://github.com/canonical/lxd/issues/13586).

2025-06-22 00:36 UTC, samuelallan72 commented
@TheSignPainter98 @NucciTheBoss I'll actually close my PRs here now that I've left the company and no longer have access to this repository. If I contribute in the future, I can open PRs from a personal fork. :)

2025-06-22 00:36 UTC, closed without merging